INSERT INTO ROLE (ID,C_VERSION, ROLE_NAME) VALUES(1, 0, 'BASIC');
INSERT INTO ROLE (ID,C_VERSION, ROLE_NAME) VALUES(2, 0, 'ADMIN');

INSERT INTO NW_USER (ID, C_VERSION, USERNAME, PASSWORD, EMAIL, USER_STATUS) VALUES(1,0, 'test', 'test', 'busradeniz89@gmail.com', 'ACTIVE');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1, 1);

INSERT INTO VIOLATION_GROUP(ID, C_VERSION, NAME) VALUES(1, 0, 'Test Violation Group');